import type { Profile, FrichyState } from "./types";

export function createSeedState(): FrichyState {
  return {
    auth: null,
    authMode: "login",
    accounts: [],
    activeView: "dashboard",
    wizardStep: 1,
    selectedFreelancerId: "fr-current",
    previewFreelancerId: "",
    profile: blankProfile("fr-current"),
    freelancers: [
      {
        id: "fr-001",
        name: "山田 太郎",
        role: "バックエンドエンジニア",
        skills: ["Java", "TypeScript", "Spring Boot", "React", "PostgreSQL"],
        yearsExperience: 6,
        desiredRate: 85,
        workRate: "週5",
        remote: "フルリモート",
        availability: "稼働可能開始日",
        lastUpdated: "2026-06-04",
        resumeName: "職務経歴書_山田太郎.pdf",
      },
      {
        id: "fr-002",
        name: "佐藤 美咲",
        role: "フロントエンドエンジニア",
        skills: ["React", "Vue", "TypeScript", "Figma"],
        yearsExperience: 4,
        desiredRate: 78,
        workRate: "週4",
        remote: "フルリモート",
        availability: "即稼働可",
        lastUpdated: "2026-06-03",
        resumeName: "skill_sheet_sato.docx",
      },
      {
        id: "fr-003",
        name: "鈴木 健",
        role: "インフラ・SRE",
        skills: ["AWS", "Terraform", "Kubernetes", "Go"],
        yearsExperience: 8,
        desiredRate: 92,
        workRate: "週5",
        remote: "一部リモート",
        availability: "即稼働可",
        lastUpdated: "2026-05-12",
        resumeName: "resume_suzuki.pdf",
      },
    ],
    jobs: [
      {
        id: "job-001",
        title: "金融SaaSのバックエンド刷新",
        client: "FinTech事業会社",
        summary:
          "Java/Spring Bootで既存決済基盤を刷新。設計から実装、テストまで担当。",
        required: ["Java", "Spring Boot", "PostgreSQL", "API設計"],
        nice: ["AWS", "React"],
        rateMin: 80,
        rateMax: 100,
        marginRate: 12,
        stream: "エンド直",
        remote: "一部リモート",
        sortFlag: true,
        active: true,
      },
      {
        id: "job-002",
        title: "人材マッチングサービスのフロント開発",
        client: "HRTechスタートアップ",
        summary:
          "React/TypeScriptで候補者・営業向け画面を改善。UI実装と状態管理が中心。",
        required: ["React", "TypeScript", "CSS"],
        nice: ["Next.js", "Figma"],
        rateMin: 70,
        rateMax: 90,
        marginRate: 10,
        stream: "1次請け",
        remote: "フルリモート",
        sortFlag: true,
        active: true,
      },
      {
        id: "job-003",
        title: "製造業向けクラウド基盤構築",
        client: "大手SIer",
        summary:
          "AWS/Terraformで新規クラウド環境を設計。監視、権限、CI/CD整備を含む。",
        required: ["AWS", "Terraform", "Linux"],
        nice: ["Kubernetes", "Go"],
        rateMin: 75,
        rateMax: 95,
        marginRate: 15,
        stream: "2次請け",
        remote: "一部リモート",
        sortFlag: false,
        active: true,
      },
    ],
    applications: [
      {
        id: "app-001",
        jobId: "job-001",
        freelancerId: "fr-001",
        status: "面談待ち",
        appliedAt: "2026-06-04",
      },
      {
        id: "app-002",
        jobId: "job-002",
        freelancerId: "fr-002",
        status: "選考中",
        appliedAt: "2026-06-03",
      },
    ],
    messages: [
      {
        id: "msg-001",
        freelancerId: "fr-001",
        from: "営業",
        to: "山田 太郎",
        body: "金融SaaS案件について、初回面談候補を確認しました。",
        at: "2026-06-04 11:20",
        readAt: "2026-06-04 11:20",
        channel: "sales",
      },
      {
        id: "msg-002",
        freelancerId: "fr-001",
        from: "山田 太郎",
        to: "営業",
        body: "6月10日午前で調整可能です。職務経歴書も更新しました。",
        at: "2026-06-04 11:36",
        readAt: "2026-06-04 11:36",
        channel: "freelancer",
      },
    ],
    meetingRequests: [
      {
        id: "meet-001",
        freelancerId: "fr-001",
        candidate: "2026-06-10 10:00",
        status: "候補",
      },
      {
        id: "meet-002",
        freelancerId: "fr-001",
        candidate: "2026-06-11 15:00",
        status: "候補",
      },
    ],
    contactInquiries: [],
    aliveChecks: [],
  };
}

export function blankProfile(id = "fr-current"): Profile {
  return {
    id,
    name: "",
    nameKana: "",
    email: "",
    phone: "",
    role: "",
    languages: "",
    db: "",
    frameworks: "",
    cloud: "",
    otherSkills: "",
    years: "",
    skillExperiences: {},
    desiredRate: "",
    startDate: "",
    workRate: "",
    remote: "",
    availability: "",
    resumeName: "",
    resumeType: "",
    resumeSize: "",
    meetingCandidates: [],
    pledgeAccepted: false,
    pledgedAt: "",
    initialMeetingCompleted: false,
    initialMeetingCompletedAt: "",
    lastUpdated: "",
  };
}
